name: Auto Claim Games

on:
  schedule:
    - cron: '0 16 * * *' # Каждый день в 19:00 по МСК
  workflow_dispatch:

jobs:
  claim:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          npm install
          npx playwright install firefox --with-deps

      - name: Run Epic Games Claimer
        run: |
          node epic-games.js --email "${{ secrets.EG_EMAIL }}" --password "${{ secrets.EG_PASSWORD }}" --totp "${{ secrets.EG_OTPKEY }}"
